### ISSUE TITLE
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by xmnlab** [pinax/pinax-invitations#33]
Hey all!

After add pinax-invitations to INSTALL_APPS django raises this error:

```
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/pinax/invitations/models.py", line 5, in <module>
    from account.models import SignupCode
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/account/models.py", line 20, in <module>
    from django.contrib.sites.models import Site
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/contrib/sites/models.py", line 80, in <module>
    class Site(models.Model):
  File "/mnt/sda1/storage/miniconda/envs/openteam/lib/python3.6/site-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
```

conda list:

```
11:18 $ conda list
# packages in environment at /mnt/sda1/storage/miniconda/envs/openteam:                                                                                         
#                                                                                                                                                               
# Name                    Version                   Build  Channel                                                                                              
asn1crypto                0.24.0                   py36_3    conda-forge                                                                                        
astroid                   2.0.2                    py36_0    conda-forge                                                                                        
atomicwrites              1.1.5                    py36_0    conda-forge                                                                                        
attrs                     18.1.0                     py_1    conda-forge                                                                                        
blinker                   1.4                        py_1    conda-forge                                                                                        
boto3                     1.8.5                      py_0    conda-forge                                                                                        
botocore                  1.11.5                     py_0    conda-forge                                                                                        
bzip2                     1.0.6                h470a237_2    conda-forge                                                                                        
ca-certificates           2018.8.24            ha4d7672_0    conda-forge                                                                                        
certifi                   2018.8.24                py36_1    conda-forge                                                                                        
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge                                                                                        
chardet                   3.0.4                    py36_3    conda-forge                                                                                        
cryptography              2.3.1            py36hdffb7b8_0    conda-forge                                                                                        
cryptography-vectors      2.3.1                    py36_0    conda-forge                                                                                        
defusedxml                0.5.0                    py36_0    conda-forge                                                                                        
django                    2.0.4                    py36_0    conda-forge                                                                                        
django-appconf            1.0.2                     <pip>                                                                                                       
django-extensions         2.1.2                      py_0    conda-forge                                                                                        
django-friendship         1.8.0                     <pip>                                                                                                       
django-haystack           2.8.1                      py_0    conda-forge                                                                                        
django-user-accounts      2.0.3                     <pip>                                                                                                       
django-widget-tweaks      1.4.2                      py_0    conda-forge                                                                                        
djangorestframework       3.8.2                      py_0    conda-forge                                                                                        
docutils                  0.14                     py36_1    conda-forge                                                                                        
drf-haystack              1.8.3                      py_0    conda-forge                                                                                        
flake8                    3.5.0                    py36_0    conda-forge
freetype                  2.9.1                h6debe1e_1    conda-forge
gunicorn                  19.9.0                   py36_0    conda-forge
idna                      2.7                      py36_2    conda-forge
isort                     4.3.4                    py36_0    conda-forge
itypes                    1.1.0                      py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
krb5                      1.16.1               hbb41f41_0    conda-forge
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libpng                    1.6.35               ha92aebf_0    conda-forge
libpq                     9.6.3                         0    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
markupsafe                1.0              py36h470a237_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
more-itertools            4.3.0                    py36_0    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
nodejs                    10.4.1                        0    conda-forge
oauthlib                  2.1.0                      py_0    conda-forge
olefile                   0.45.1                     py_1    conda-forge
openssl                   1.0.2p               h470a237_0    conda-forge
pdfminer.six              20170720                 py36_0    conda-forge
pillow                    5.2.0            py36hc736899_1    conda-forge
pinax-invitations         6.1.2                     <pip>
pip                       18.0                     py36_1    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
psycopg2                  2.7.5            py36hdffb7b8_1    conda-forge
py                        1.6.0                      py_0    conda-forge
pycodestyle               2.3.1                      py_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyflakes                  1.6.0                      py_1    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pylint                    2.1.1                    py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pysocks                   1.6.8                    py36_2    conda-forge
pytest                    3.7.4                    py36_0    conda-forge
pytest-django             3.4.2                      py_0    conda-forge
pytest-django-haystack    0.3.0                      py_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-coreapi            2.3.3                      py_0    conda-forge
python-coreschema         0.0.4                      py_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python3-openid            3.1.0                    py36_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py36_1    conda-forge
requests-oauthlib         1.0.0                      py_1    conda-forge
s3transfer                0.1.13                   py36_0    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
simplejson                3.16.0           py36h470a237_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
social-auth-app-django    2.1.0                      py_0    conda-forge
social-auth-core          1.7.0                      py_0    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tk                        8.6.8                         0    conda-forge
typed-ast                 1.1.0                    py36_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
uritemplate               3.0.0                      py_1    conda-forge
urllib3                   1.23                     py36_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
whoosh                    2.7.4                      py_1    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

any idea to workaround this issue?

**Comment by xmnlab** [comment]
I fixed that adding 'django.contrib.sites' and 'account' to INSTALL_APPS

**Comment by AlekseiMarinichenko** [comment]
The similar problem. Adding 'django.contrib.sites' and 'my_app' to INSTALL_APPS does not help.
Any ideas?

**Comment by KatherineMichel** [comment]
@AlekseiMarinichenko What app are you trying to add to INSTALL_APPS?

**Comment by Santosh155** [comment]
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 350, in execute
    self.check()
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 60, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/advancetradingne/public_html/python/advance/urls.py", line 23, in <module>
    path('', include('Home.urls')),
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/advancetradingne/public_html/python/Home/urls.py", line 3, in <module>
    from . import views
  File "/home/advancetradingne/public_html/python/Home/views.py", line 2, in <module>
    from brands.models import Name, Brand
  File "/home/advancetradingne/public_html/python/brands/models.py", line 7, in <module>
    class Name(models.Model):
  File "/home/advancetradingne/virtualenv/public__html_python/3.6/lib/python3.6/site-packages/django/db/models/base.py", line 95, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class brands.models.Name doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by MichaelAchterberg** [comment]
I'm getting the same error, any ideas what package I need to have in INSTALLED_APPS?

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "c:\wexlog1\wexlog\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\management\base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\management\base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "c:\wexlog1\wexlog\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "c:\wexlog1\wexlog\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\wexlog1\wexlog\lib\site-packages\django\urls\resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\wexlog1\wexlog\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\wexlog1\wexlog\lib\site-packages\django\urls\resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files (x86)\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\wexlog1\wexlog\wexlog_1\WeXlog\urls.py", line 12, in <module>
    path('accounts/', include('allauth.urls')),
  File "c:\wexlog1\wexlog\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files (x86)\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\wexlog1\wexlog\lib\site-packages\allauth\urls.py", line 10, in <module>
    urlpatterns = [url(r'^', include('allauth.account.urls'))]
  File "c:\wexlog1\wexlog\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files (x86)\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\wexlog1\wexlog\lib\site-packages\allauth\account\urls.py", line 3, in <module>
    from . import views
  File "c:\wexlog1\wexlog\lib\site-packages\allauth\account\views.py", line 18, in <module>
    from ..utils import get_form_class, get_request_param
  File "c:\wexlog1\wexlog\lib\site-packages\allauth\utils.py", line 11, in <module>
    from django.contrib.sites.models import Site
  File "c:\wexlog1\wexlog\lib\site-packages\django\contrib\sites\models.py", line 78, in <module>
    class Site(models.Model):
  File "c:\wexlog1\wexlog\lib\site-packages\django\db\models\base.py", line 111, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class django.contrib.sites.models.Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by bappi2016** [comment]
Just add Django's Sites framework to your apps and set SITE_ID to 1 in your settings.

INSTALLED_APPS = [
    ...
    'django.contrib.sites',
]

SITE_ID = 1

**Comment by Syed-Mujeeb** [comment]
@bappi2016 It doesn't solve the problem. Still, it raising the error

**Comment by sarahghanei** [comment]
if your problem is in python console, just stop it and run it again. because your py console have been running before adding your new apps to setting.py-> INSTALLED_APPS.

**Comment by tonmoyazad** [comment]
is it essential to have xcode to be installed to MySQLClient work properly? 

terminal was asking did I install mysqlclient?
then I've added this at __init__.py

import pymysql
pymysql.install_as_MySQLdb()

then is showing:
Site doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
even I've added 

INSTALLED_APPS = [
...
'django.contrib.sites',
]

SITE_ID = 1

**Comment by OxwardInc** [comment]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\KelMcAnthony\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\KelMcAnthony\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\core\management\base.py", line 475, in check
    all_issues = checks.run_checks(
  File "D:\Wallet\wallet-venv\lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
  File "D:\Wallet\wallet-venv\lib\site-packages\django\urls\resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "D:\Wallet\wallet-venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Wallet\wallet-venv\lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\KelMcAnthony\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Wallet\wallet\wallet\urls.py", line 18, in <module>
    from core.views import signup
  File "D:\Wallet\wallet\core\views.py", line 5, in <module>
    from core.models import Transaction
  File "D:\Wallet\wallet\core\models.py", line 6, in <module>
    class User(AbstractUser):
  File "D:\Wallet\wallet-venv\lib\site-packages\django\db\models\base.py", line 132, in __new__
    raise RuntimeError(
RuntimeError: Model class core.models.User doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by joebuggy561** [comment]
I have tried all these systems but i still have the same error occurring I think it has something to do with the AUTH_USER_MODEL, once that is removed everything seems to be working just fine

**Comment by uhurusurfa** [comment]
> I have tried all these systems but i still have the same error occurring I think it has something to do with the AUTH_USER_MODEL, once that is removed everything seems to be working just fine

@joebuggy561  You will need to provide more detailed information for someone to be able to help you. I assume you are removing AUTH_USER_MODEL from your settings.py which means it will default to the Django provided value. What value are you trying to use in your settings file?

**Comment by AsarehSKP** [comment]
hello all seniors  i have same error while I`m completing  the login authenticating . 
i dont know why pycharm doesnt let complete migrations . 
please if you had same error help me , Thank you . 

(.venv) PS C:\Users\Asareh\PycharmProjects\Radin\radinproject> python manage.py runserver 9090
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Asareh\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Asareh\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\core\management\commands\runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\core\checks\urls.py", line 44, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\core\checks\urls.py", line 63, in _load_all_namespaces
    url_patterns = getattr(resolver, "url_patterns", [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\urls\resolvers.py", line 718, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\urls\resolvers.py", line 711, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Asareh\PycharmProjects\Radin\radinproject\radinproject\urls.py", line 23, in <module>
    path('', include('User_app.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Asareh\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Asareh\PycharmProjects\Radin\radinproject\User_app\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\Asareh\PycharmProjects\Radin\radinproject\User_app\views.py", line 1, in <module>
    from allauth.account.forms import LoginForm
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\allauth\account\forms.py", line 11, in <module>
    from allauth.account.internal import flows
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\allauth\account\internal\__init__.py", line 1, in <module>
    from allauth.account.internal import flows
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\allauth\account\internal\flows\__init__.py", line 1, in <module>
    from allauth.account.internal.flows import (
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\allauth\account\internal\flows\email_verification.py", line 9, in <module>
    from allauth.account.models import EmailAddress
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\allauth\account\models.py", line 23, in <module>
    class EmailAddress(models.Model):
  File "C:\Users\Asareh\PycharmProjects\Radin\Radin\.venv\Lib\site-packages\django\db\models\base.py", line 134, in __new__
    raise RuntimeError(
RuntimeError: Model class allauth.account.models.EmailAddress doesn't declare **an explicit app_label and isn't in an application in INSTALLED_APPS.**
