### ISSUE TITLE
RuntimeError in django . How Eliminate this?

### ISSUE THREAD

**Issue by Dastanio** [pinax/pinax-invitations#35]
HEEELP PLEASE thats django Error
    return check_resolver(resolver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\urls.py", line 20, in <module>
    path('articles/', include('myfirst.apps.articles.urls')),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\apps\articles\urls.py", line 3, in <module>
    from . import views
  File "D:\Django\myfirst\myfirst\apps\articles\views.py", line 3, in <module>
    from .models import Article, Comment
  File "D:\Django\myfirst\myfirst\apps\articles\models.py", line 5, in <module>
    class Article(models.Model):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\db\models\base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class myfirst.apps.articles.models.Article doesn't declare a
n explicit app_label and isn't in an application in INSTALLED_APPS.
D:\Django\myfirst\myfirst\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\urls.py", line 20, in <module>
    path('articles/', include('myfirst.apps.articles.urls')),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\apps\articles\urls.py", line 3, in <module>
    from . import views
  File "D:\Django\myfirst\myfirst\apps\articles\views.py", line 3, in <module>
    from .models import Article, Comment
  File "D:\Django\myfirst\myfirst\apps\articles\models.py", line 5, in <module>
    class Article(models.Model):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\db\models\base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class myfirst.apps.articles.models.Article doesn't declare a
n explicit app_label and isn't in an application in INSTALLED_APPS.
D:\Django\myfirst\myfirst\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\urls.py", line 20, in <module>
    path('articles/', include('myfirst.apps.articles.urls')),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\apps\articles\urls.py", line 3, in <module>
    from . import views
  File "D:\Django\myfirst\myfirst\apps\articles\views.py", line 3, in <module>
    from .models import Article, Comment
  File "D:\Django\myfirst\myfirst\apps\articles\models.py", line 5, in <module>
    class Article(models.Model):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\db\models\base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class myfirst.apps.articles.models.Article doesn't declare a
n explicit app_label and isn't in an application in INSTALLED_APPS.
D:\Django\myfirst\myfirst\settings.py changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\threading.py
", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 392, in check
    all_issues = self._run_checks(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\management\base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\urls.py", line 20, in <module>
    path('articles/', include('myfirst.apps.articles.urls')),
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\importlib\__
init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Django\myfirst\myfirst\apps\articles\urls.py", line 3, in <module>
    from . import views
  File "D:\Django\myfirst\myfirst\apps\articles\views.py", line 3, in <module>
    from .models import Article, Comment
  File "D:\Django\myfirst\myfirst\apps\articles\models.py", line 5, in <module>
    class Article(models.Model):
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-package
s\django\db\models\base.py", line 112, in __new__
    raise RuntimeError(
RuntimeError: Model class myfirst.apps.articles.models.Article doesn't declare a
n explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by KatherineMichel** [comment]
@Dastanio It sounds like there is an app in your project that is not actually listed in the settings.py `INSTALLED_APPS` section.

**Comment by KatherineMichel** [comment]
@Dastanio Were you able to resolve this?
